### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Benji377** [vincentrussell/java-ini-parser#1]
First of all, thank you very much for providing the exact tolls at the perfect time I needed them. I tried to use the [ini4j library](http://ini4j.sourceforge.net/index.html) but it was deprecated and giving me strange errors.
I luckily found your library and downloaded the JAR from the [maven repository](https://mvnrepository.com/artifact/com.github.vincentrussell/java-ini-parser/1.0).
I then added it to my project, but when I run it I immediately hit an Exception. After looking around on the ineternet for a little bit I found out that the reason for the exception was a missing library. I was missing the [Apache lang3 library](https://commons.apache.org/proper/commons-lang/download_lang.cgi). After installing it everything worked fine.

Here is the whole exception I got:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/mutable/MutableObject
	at com.github.vincentrussell.ini.Ini.load(Ini.java:48)
	at ErgoartikelnummerReader.<init>(ErgoartikelnummerReader.java:15)
	at MainExporter.<clinit>(MainExporter.java:20)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.mutable.MutableObject
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 3 more

Process finished with exit code 1
```
Note: ErgoartikelnummerReader and MainExporter are classes I coded and they initialize the Ini parser.
I am using Jetbrains Intellij IDEA 2021.2.1(Community edition) with Openjdk 16.0.2

**Comment by Benji377** [comment]
After finding [this question on Stackoverflow](https://stackoverflow.com/questions/3468027/java-lang-noclassdeffounderror-org-apache-commons-lang-validate) I quickly realised that it was very similar to my exception and therefore tried to download the [Apache commons lang3 library](https://commons.apache.org/proper/commons-lang/download_lang.cgi). After adding it to the project everything worked fine. This issue is therefore already solved.

**Comment by vincentrussell** [comment]
if you import the library as a maven dependency:

<dependency>
   <groupId>com.github.vincentrussell</groupId>
   <artifactId>java-ini-parser</artifactId>
   <version>1.0</version>
</dependency>

it will pull in all the required libraries as well.

**Comment by Benji377** [comment]
True, just wanted to point out that if you use the raw jar file and encounter a similar error there is a way to solve it.
