### ISSUE TITLE
Multi-line comments

### ISSUE THREAD

**Issue by Almighty-Satan** [vincentrussell/java-ini-parser#5]
```java
var ini = new Ini();
ini.putValue("section0", "hello", "world");
try (var fileWriter = new FileWriter("test.ini")) {
    ini.store(fileWriter, "Test" + System.lineSeparator() + "[section1]" + System.lineSeparator() + "test=123");
}
```
The code above produces the following ini file:
```ini
#Test
[section1]
test=123
[section0]
hello = world
```
instead of 
```ini
#Test
#[section1]
#test=123
[section0]
hello = world
```
Is this intended behavior?
The documentation for `Ini#store` reads "commments [sic] to put at the top of the file". The variable is also named `comments` (Plural). Due to this I'd assume that multi-line comments should be possible and would be escaped correctly, however this does not appear to be the case.

**Comment by vincentrussell** [comment]
see: a77dfc6074317e06e55842c4def8899442a19232

Let me know if you need a new release cut.

Thanks for identifying the issue
-Vincent

**Comment by Almighty-Satan** [comment]
Thanks for your quick response. a77dfc6 looks good to me but I didn't test it. I don't need a release for this, just noticed it while testing.
