### ISSUE TITLE
getValue() method should be able to handle nonexistent keys

### ISSUE THREAD

**Issue by DonaldDuck313** [vincentrussell/java-ini-parser#6]
If attempting to get a nonexistent key with `getValue()`, currently it throws a `NullPointerException`. This isn't very intuitive and isn't documented anywhere. It would be better if `getValue()` returned null if the key doesn't exist.

**Comment by vincentrussell** [comment]
I just wrote this test and it passes:

    @Test
    public void getValueNonExistingKey() throws IOException {
        Ini ini = new Ini();
        assertNull(ini.getValue("SECTIONDOESNT_EXIST", "NOT_FOUND_sdfadfdsafd"));
    }


Can you write a test or provide some code that demonstrates your issue?   Also, which version of the library are you using?

**Comment by DonaldDuck313** [comment]
It seems like this problem only happens on the overload of `getValue` that takes three parameters. So this variation of your test should demonstrate my issue:

```java
@Test
public void getValueNonExistingKey() throws IOException {
    Ini ini = new Ini();
    assertNull(ini.getValue("SECTIONDOESNT_EXIST", "NOT_FOUND_sdfadfdsafd", String.class));
}
```

**Comment by vincentrussell** [comment]
thank you for the test.  I've patched the issue and  will do a release hopefully by tomorrow.
